// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using GoalStats.Template.Api.Infrastructure.Database;

#nullable disable

namespace GoalStats.Template.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20260908043250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoalStats.Template.Api.Models.ActionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Actions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Actions_Name_NotBlank", "\"Name\" ~ '[^[:space:]]'");

                            t.HasCheckConstraint("CK_Actions_Type", "\"Type\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("GoalStats.Template.Api.Models.ItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Items", null, t =>
                        {
                            t.HasCheckConstraint("CK_Items_Name_NotBlank", "\"Name\" ~ '[^[:space:]]'");

                            t.HasCheckConstraint("CK_Items_Status", "\"Status\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("GoalStats.Template.Api.Models.ActionModel", b =>
                {
                    b.HasOne("GoalStats.Template.Api.Models.ItemModel", "Item")
                        .WithMany("Actions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GoalStats.Template.Api.Models.ItemModel", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
